version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: algoTrader
      POSTGRES_PASSWORD: algoTrader
      POSTGRES_DB: portfolio
    network_mode: "host"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  node:
    build: .
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: localhost
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
    network_mode: "host"

volumes:
  postgres-data: